apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular
  name: angular-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular
  type: LoadBalancer